server:
  port: 8080

spring:
  application:
    name: terminkalender
  profiles:
    active: prod  # Azure MySQL Production als Standard

# Production-Ready Logging
logging:
  level:
    de.swtp1.terminkalender: INFO
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false  # Mail Health Check deaktivieren da kein SMTP konfiguriert
  info:
    env:
      enabled: true
