server:
  port: 8080

spring:
  application:
    name: terminkalender
  
  # H2 Database Configuration (Development)
  datasource:
    url: jdbc:h2:file:./data/terminkalender;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  # H2 Console (Development only)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging Configuration
logging:
  level:
    de.swtp1.terminkalender: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
