server:
  port: 8080

spring:
  application:
    name: terminkalender
  profiles:
    active: prod  # Azure MySQL Production als Standard

# Production-Ready Logging
logging:
  level:
    de.swtp1.terminkalender: INFO
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false  # Mail Health Check deaktivieren da kein SMTP konfiguriert
  info:
    env:
      enabled: true

# Spring Boot Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,beans,mappings
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
  metrics:
    export:
      simple:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true
    jvm:
      enabled: true
    system:
      enabled: true
