spring:
  application:
    name: terminkalender-test
  
  # H2 Test Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  # JPA Test Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Logging für Tests
logging:
  level:
    de.swtp1.terminkalender: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
